### ISSUE TITLE
Install utilities : git and maybe other

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-docker#13]
The image doesn't have git, so the generator fails when it launches `bower install`

@indyaah : why did you remove utilities in https://github.com/jhipster/jhipster-docker/pull/12 ? Probably for saving space but I think there are utilities that the user can need (example : vim), zip/bzip2 (maybe for sub generator cloud?), fontconfig (maybe for languages?)

These lines are important :
```
# install utilities		
RUN apt-get -y install vim git sudo zip bzip2 fontconfig curl
```

**Comment by indyaah** [comment]
Yeah, I thought they are not being used, guess it was a mistake.
I am going to add them back.

**Comment by pascalgrimaud** [comment]
PR done : https://github.com/jhipster/jhipster-docker/pull/14
I close this issue
