### ISSUE TITLE
Deprecated repo

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-docker#21]
@jdubois: can this repo be marked as deprecated?

But don't delete it, let's keep history/the story;-)

**Comment by jdubois** [comment]
I missed something here, isn't the jhipster/jhipster Docker image built from this repo?

**Comment by pascalgrimaud** [comment]
I explained here https://github.com/jhipster/generator-jhipster/issues/2754
It uses the Dockerfile from generator-jhipster

Im on my phone, I will complete my answer if needed, monday

**Comment by jdubois** [comment]
On my phone too :-)
I'll test this, but yes I agree this should be deprecated.

**Comment by jdubois** [comment]
OK I've had a look and it should be deprecated.
