### ISSUE TITLE
Update nodeJS repository to new official one

### ISSUE THREAD

**Issue by josetesan** [jhipster/jhipster-docker#4]
Kindly check https://nodesource.com/blog/chris-lea-joins-forces-with-nodesource, as chris-lea is no longer updating nodeJS repository up to date.

**Comment by drissamri** [comment]
I have updated the node version to solve the npm issue in #1353 and then saw your ticket. So both are fixed now. ;-)

I'm not that experienced in either linux, docker and or node so feel free to improve the install procedure.

**Comment by drissamri** [comment]
If this pull request is accepted, it might be good to also comment on my answer on a related [stackoverflow issue](http://stackoverflow.com/questions/28820950/unable-to-successfully-create-jhipster-project-using-docker-image-and-install-in/29582318#29582318)
